# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty

# env:
#   global:
#     - MAKEFLAGS="-j 2"

before_script:
  - set -e
  - make -j2 install-deps
  - set +e

script:
  - set -e
  - make -j2 check
  - if [[ `git status -s` ]]; then
      echo "Files changed by build! Did you forget to commit some Roxygen output?";
      exit 1;
    fi
  - set +e
